name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            cd ~/cloud-url-shortener
            git pull

            cd urlshortener
            mvn clean package -DskipTests
            sudo cp target/urlshortener-0.0.1-SNAPSHOT.jar /opt/urlshortener/urlshortener.jar
            sudo systemctl restart urlshortener

            cd ../frontend
            npm install
            npm run build
            sudo rm -rf /var/www/html/*
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx